apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus-svc-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: multus-svc-controller
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: multus-svc-controller
  namespace: default
subjects:
- kind: ServiceAccount
  name: multus-svc-controller
roleRef:
  kind: Role
  name: multus-svc-controller
  apiGroup: rbac.authorization.k8s.io
