apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd-svc
  name: httpd-svc
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32001
  selector:
    app: httpd
  type: NodePort
