apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-helm
  labels:
    app: httpd-helm
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: httpd-helm
  template:
    metadata:
      labels:
        app: httpd-helm
    spec:
      containers:
      - name: httpd-helm
        image: {{ .Values.image.name }}
