apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: httpd-svc
spec:
  ports:
  - name: "80"
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: httpd
  type: ClusterIP
