apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info
  namespace: {{ .Values.namespace }}
  labels:
    app: pod-info
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: pod-info
  template:
    metadata:
      labels:
        app: pod-info
    spec:
      containers:
      - name: pod-info
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: pod-info-config
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: pod-info-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pod-info-secret
                key: DB_PASSWORD
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: pod-info-secret
                key: API_KEY
        volumeMounts:
          - name: config-vol
            mountPath: /etc/pod-info-config
          - name: secret-vol
            mountPath: /etc/pod-info-secret
            readOnly: true
      volumes:
        - name: config-vol
          configMap:
            name: pod-info-config
        - name: secret-vol
          secret:
            secretName: pod-info-secret
