apiVersion: v1
kind: Secret
metadata:
  name: pod-info-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.secret.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
  API_KEY: {{ .Values.secret.apiKey | b64enc | quote }}
