apiVersion: apps/v1
kind: Deployment
metadata:
  name: devtools-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devtools
  template:
    metadata:
      labels:
        app: devtools
    spec:
      containers:
      - name: devtools
        image: 961341535886.dkr.ecr.ap-southeast-2.amazonaws.com/devtools:ubi-latest
        stdin: true
        tty: true
        env:
        - name: test
          value: test
        ports:
        - name: test-port1
          containerPort: 8292
