apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  description: "My project with full access"
  
  # Allow from any repo
  sourceRepos:
    - '*'

  # Allow deploy to any cluster and namespace
  destinations:
    - namespace: '*'
      server: '*'

  # Allow all resource kinds (cluster-scoped and namespace-scoped)
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  # Full access roles
  roles:
    - name: admin
      description: Full access
      policies:
        - p, proj:my-project:admin, applications, *, my-project/*, allow
      groups:
        - '*'
