apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akxrepo/lab.git
    targetRevision: HEAD
    path: argocd/httpd-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: httpd
