apiVersion: v1
kind: Pod

metadata:
  name: multus-test

  annotations:
    k8s.v1.cni.cncf.io/networks: secondary-net

spec:

  containers:

  - name: test

    image: alpine

    command:
      - sleep
      - infinity

    securityContext:
      capabilities:
        add:
        - NET_ADMIN
