apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Values.backend.serviceAccount.name }}
  labels:
{{ include "pod-info-three-tier.labels" . | indent 4 }}
{{- if .Values.commonLabels }}
{{ toYaml .Values.commonLabels | indent 4 }}
{{- end }}
  annotations:
{{- if .Values.commonAnnotations }}
{{ toYaml .Values.commonAnnotations | indent 4 }}
{{- end }}
