apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Values.frontend.service.name }}
  labels:
{{ include "pod-info-three-tier.labels" . | indent 4 }}
{{- if .Values.commonLabels }}
{{ toYaml .Values.commonLabels | indent 4 }}
{{- end }}
  annotations:
{{- if .Values.frontend.service.annotations }}
{{ toYaml .Values.frontend.service.annotations | indent 4 }}
{{- else if .Values.commonAnnotations }}
{{ toYaml .Values.commonAnnotations | indent 4 }}
{{- end }}
spec:
  selector:
    app: pod-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  type: {{ .Values.frontend.service.type }}
