FROM alpine:3.22

RUN apk add --no-cache \
    bash \
    curl \
    wget \
    bind-tools \
    iputils \
    iproute2 \
    busybox-extras \
    net-tools \
    jq \
    tcpdump \
    traceroute \
    mtr \
    openssl \
    procps \
    util-linux \
    socat \
    vim \
    less

WORKDIR /workspace

CMD ["bash"]
