apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: enx2-net-dynamic
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enX2",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.27.0/24",
        "range_start": "10.0.27.50",
        "range_end": "10.0.27.100",
        "gateway": "10.0.27.1"
      }
    }
